### ISSUE TITLE
Loading datafile with drag and drop raises extension error

### ISSUE THREAD

**Issue by maximelucas** [luphysics/PyMODA#5]
When loading a datafile: loading from "Browse" works fine, but when loading by "Drag and Dropping", there is an error popup: 
`"Cannot parse a file with the extension: .mat"`

I think in `parsing.py`, an error is raised no matter the extension, see log:
```
Welcome to PyMODA. Please do not close this terminal window while PyMODA is running.
Opening /home/maxime/Nextcloud/WORK/SCIENCE/special_issue/images/signal_timevar_2.mat
...
Calculation terminated.
Traceback (most recent call last):
  File "/home/maxime/Documents/pyMODA/src/gui/Application.py", line 43, in start_time_frequency
    self.open_window(TFWindow)
  File "/home/maxime/Documents/pyMODA/src/gui/Application.py", line 67, in open_window
    window = WindowType(self)
  File "/home/maxime/Documents/pyMODA/src/gui/windows/timefrequency/TFWindow.py", line 65, in __init__
    self.presenter.init()
  File "/home/maxime/Documents/pyMODA/src/gui/windows/common/BaseTFPresenter.py", line 59, in init
    self.view.select_file()
  File "/home/maxime/Documents/pyMODA/src/gui/windows/common/BaseTFWindow.py", line 56, in select_file
    self.presenter.on_file_selected(file_path)
  File "/home/maxime/Documents/pyMODA/src/gui/windows/common/BaseTFPresenter.py", line 125, in on_file_selected
    self.load_data()
  File "/home/maxime/Documents/pyMODA/src/gui/windows/timefrequency/TFPresenter.py", line 188, in load_data
    self.signals = Signals.from_file(self.open_file)
  File "/home/maxime/Documents/pyMODA/src/maths/signals/Signals.py", line 135, in from_file
    parser = get_parser(file)
  File "/home/maxime/Documents/pyMODA/src/data/parsing/parsing.py", line 49, in get_parser
    raise ParsingException(f"Cannot parse a file with the extension: {extension}")
data.parsing.parsing.ParsingException: Cannot parse a file with the extension: .mat
```

Once this error occurs, after restaring pyMODA, and lauching the "Time-Frequency" module, the error 
`addItems(self, Iterable[str]): argument 1 has unexpected type 'str`
immediately pops up (and again when trying to load files). Deleting `settings.cong` solves that second error.

**Comment by spmccormack** [comment]
Ah, that's interesting. Are you using macOS or Linux?

**Comment by maximelucas** [comment]
I'm using Linux.

**Comment by spmccormack** [comment]
This is a pretty bizarre bug - when I call the `get_parser()` function with the same file path, it works fine (both on Windows and on Manjaro Linux).

Could you let me know:

1. Which Linux distribution you're using?
2. Which version of Python you're using?

**Comment by maximelucas** [comment]
1. Ubuntu 18.04.3 LTS
2. Python 3.6.9

It does seem strange: browsing or drag and dropping select the same file. Then clicking "ok" to load the same file leads to different outcomes depending on how the file path was selected. Although I guess clicking "ok" should call the same `get_parser()` function on the same file path?

**Comment by spmccormack** [comment]
I've fixed it after trying on the GNOME desktop environment. For some reason, the drag-and-drop data ends in `\r\n` so the `get_parser()` function was comparing `.mat\r\n` to `.mat`, etc.
